"""changed member field in prayer to boolean and renamed it to is_member

Revision ID: 881e5fdc3999
Revises: fe45ca3b94c3
Create Date: 2025-02-02 01:03:10.068038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881e5fdc3999'
down_revision = 'fe45ca3b94c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_member', sa.Boolean(), nullable=True))
        batch_op.drop_column('member')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member', sa.INTEGER(), nullable=True))
        batch_op.drop_column('is_member')

    # ### end Alembic commands ###
