"""added title field to prayer

Revision ID: e2966ca38a42
Revises: 881e5fdc3999
Create Date: 2025-02-02 01:06:11.051063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2966ca38a42'
down_revision = '881e5fdc3999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
